name: build

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: compile
      - run: ls
      - run: meson setup builddir
      - run: cat builddir/build.ninja
      - run: meson compile -C builddir
      # - run: cargo build --release
      # - uses: actions/upload-artifact@v3
      #   with:
      #     name: gtk-qq
      #     path: target/release/gtk-qq
