name: check

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-22.04
    # container:
    #   image: ghcr.io/gtk-rs/gtk4-rs/gtk4:latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          default: true
      - run: sudo apt-get update
      - run: sudo apt-get install meson ninja-build
      - run: meson setup builddir
      - run: meson compile -C builddir
      - run: cargo fmt
      - run: cargo clippy


    