name: check

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - main
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-22.04
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy, rustfmt
          default: true
      - run: sudo apt-get update
      - run: sudo apt-get install meson ninja-build libgtk-4-dev libadwaita-1-dev
      - run: meson setup builddir
      - run: meson compile -C builddir
      - run: cargo fmt --check
      - run: cargo clippy
